### ISSUE TITLE
Change name of Groups to Roles?

### ISSUE THREAD

**Issue by jonzenor** [jonzenor/MWSubmissionManager#11]
Discuss!

We're not really using this in the traditional term of groups, where users can see what all groups they are in and request what they need or anything. It is more of just what role the user has on the site, so should we rename it before things get too deep, or just leave it?

We can totally just leave it and just call it Roles on the front end HTML, but leave groups as all the backend database stuff.

**Comment by Pieomon** [comment]
In my head Groups makes sense cuz that's how user permissions are in a linux environment (done by groups)

**Comment by jonzenor** [comment]
That works for me.
