### ISSUE TITLE
Change name to legal_name?

### ISSUE THREAD

**Issue by jonzenor** [jonzenor/MWSubmissionManager#31]
We should make it so legal_name is the legal name. We should have a "name" field in the user model, but not in the database. The user model will be set name to be either legal name or pen name, whichever is appropriate.

This way in our code we can always reference $user->name to show the desired name for the user.

Otherwise, if we don't want to do it that way, then pen_name should be name in the database and the legal_name should be something different. This way when we are using $user->name we always get the pen name. If we go this route then the registration form needs to be updated to require pen name and legal name.

**Comment by Pieomon** [comment]
I've been having trouble overriding $user->name to produce the name.  When I try to do it, the PHP code complains I'm not returning the correct type of data.  I've made a display_name function for User and CurrentUser.  Since we more control CurrentUser I could make it's ->name return Legal/Author.
