### ISSUE TITLE
Can't migrate anymore - Pie dev build

### ISSUE THREAD

**Issue by Pieomon** [jonzenor/MWSubmissionManager#69]
Well, seems renaming the database files outright broke my box.  Now I can't pull in your migration files because it says I can't find it.

"[mwsubmissions@rcentral513 MWSubmissionManager]$ php artisan migrate:reset
Migration not found: 2017_08_20_185449_Default_Permissions_for_PenaltyBox_Group"

Running composer dump-autoload doesn't work, nor does php artisan optimize.  

Right now trying to figure out how to manually rebuild migrations from scratch to get my box back up.  I don't think 1.0 is getting done super quick due to this as the pie-website doesn't run anymore.
https://github.com/jonzenor/MWSubmissionManager

**Comment by jonzenor** [comment]
I'm really sorry about that. This reminds me, when we move the live site to 0.1 we need to FIRST do a migrate:reset, then git pull. That should allow things to upgrade more smoothly.

**Comment by Pieomon** [comment]
Migration completed!  Needed to do the following steps:

Delete everything from the migration table (from cPanel)
Drop all tables except migrations.
Run php artisan migrate.
